### ISSUE TITLE
can't compile, even have a glibc-devel  

### ISSUE THREAD

**Issue by ngarridon** [ac000/libac#16]
hi, this is my output when tries to compile : "make rpm"
-e Building: rpm
Building 1.99.0-104-gc680697
error: Failed build dependencies:
	glibc-devel is needed by libac-1.99.0-1.x86_64
make: *** [Makefile:22: rpm] Error 11

but i have glibc-devel (i'm in a deian 11 envronment)

**Comment by ac000** [comment]
On Sat, 16 Jul 2022 22:28:33 -0700
ngarridon ***@***.***> wrote:

> hi, this is my output when tries to compile : "make rpm"
> -e Building: rpm
> Building 1.99.0-104-gc680697
> error: Failed build dependencies:
> 	glibc-devel is needed by libac-1.99.0-1.x86_64
> make: *** [Makefile:22: rpm] Error 11
> 
> but i have glibc-devel (i'm in a deian 11 envronment)

Ah, your trying to build a rpm package, that won't work on Debian.
Unfortunately I don't currently support building a dpkg.

What happens if you just do 'make' ?

I've also updated bingo to allow it compile against a libac in its
source directory.

So once you have libac built. Do a 'git pull origin master' in the
bingo repository then you can build with

  $ CFLAGS="-I../libac/src/include" LDFLAGS="-L../libac/src" make

It needs gtk3/-devel and glib2/-devel

Then you can run it like

  $ LD_LIBRARY_PATH=../libac/src ./bingo

Try that...

**Comment by ngarridon** [comment]
thank so much for your support and for sharing, everything is functioning. appreciated.

**Comment by ac000** [comment]
Great!
